### ISSUE TITLE
error: formula for std dev of discrete distribution shown instead of variance

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-uniform-distribution#2]
in The Discrete Uniform Distribution section:

> $$Var(X) = \sqrt{\frac{(b-a)(b-a+2)}{12}}$$

should be

> $$Var(X) = \frac{(b-a)(b-a+2)}{12}$$

**Comment by bpurdy-ds** [comment]
Correct, and corrected, with commit: https://github.com/learn-co-curriculum/dsc-uniform-distribution/issues/2#issue-518665756
